# используем язык java. Travis CI поддерживает другие языки тоже.
#env:
#  global:
#    - CODECOV_TOKEN="47b6c95f-283e-4cfe-b7a6-c619bcc8539c"

language: java
dist: bionic
jdk:
  - openjdk14


# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
#after_success:
#  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту youremail@smtp.ru (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - velesov7493@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always